const data = [
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
  {
    name: 'Hack Your Future',
    description: 'HackYourFuture was founded in 2015 in Amsterdam, with the aim to enable refugees to build digital skills for a career in web development, facilitate the integration of newcomers, and address the shortage of qualified workforce in the IT sector. Since 2015, HackYourFuture coding schools have also opened in Copenhagen and Malmö.',
    logo: 'https://hackyourfuture.be/img/hyflbe.jpg',
    url: 'https://hackyourfuture.be/',
    address: 'BeCentral, Cantersteen 12, 1000 Bruxelles',
    contactNumber: '0032489785015',
    email: 'contact@hackyourfuture.be',
  },
]
export default data;
